---
# base role - handlers/main.yml - role handlers

- name: restart cron
  systemd:
    name: cron
    state: restarted

- name: restart ssh
  listen: restart_ssh
  service:
    name: ssh
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted

- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
