---
# base role - defaults/main.yml - default values for role vars

locale: en_US.UTF-8
tz: Etc/UTC

# apt_packages documentation:
# - net-tools includes useful tools like `ifconfig`
# - rsync is useful for sync'ing files + folders to the device
# - psmisc includes useful utilities like `killall`
# - rsyslog + rsyslog-gnutls enable sending system logs to remote targets
# - ufw is a universal firewall (a typical choice for ubuntu servers)
# - fail2ban w/ default config helps mitigate ssh brute force attacks
# - openssl provides tools for security + cryptography
# - ca-certificates adds common ca (certificate authority) certificates

base_apt_packages:
  - ntp
  - tzdata
  - rsyslog
  - rsyslog-gnutls
  - net-tools
  - rsync
  - psmisc
  - ufw
  - fail2ban
  - openssl
  - ca-certificates

ufw_policy_default:
  - { direction: "incoming", policy: "deny" }
  - { direction: "outgoing", policy: "allow" }

ufw_rules_ssh:
  - { rule: "allow", port: '{{ ssh_port | default("22") }}', protocol: "tcp" }
