- name: deploy OliviaParty PartyBoxes in lightweight dedicated kiosk configuration
  hosts: intelboards
  become: true
  vars:
    kiosk_url: "https://projects.firxworx.com/olivia-joystick-nextjs"
    display_resolution: 1366x768 # 1920x1080 # string in format: {digits}x{digits} e.g. "1920x1080", "1366x768", etc.
  roles:
    - base
    - xserver
    - chromium
    - kiosk
  tasks:
    - name: done
      debug:
        msg: success
